controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\data\ActiveDataProvider;
use app\models\Ciclista;
use app\models\Equipo;
use app\models\Puerto;
use app\models\Lleva;
use app\models\Etapa;
use yii\data\SqlDataProvider;
use yii\db\Query;


class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
    
    
    
    /*Este método se usa para mostrar el ListView*/
    public function actionMostrarciclistas(){
        $dataProvider = new ActiveDataProvider ([
            'query' => Ciclista::find(),
        ]);
        return $this->render("ciclistas",[
            "dataProvider"=>$dataProvider,
        ]);
    }
     
    
    public function actionMostrarequipos(){
        $dataProvider = new ActiveDataProvider([
        'query' => Equipo::find(),
        'pagination' => [
            'pageSize' => 12, // Ajusta según sea necesario
        ],
    ]);

    return $this->render('equiposs', [
        'dataProvider' => $dataProvider,
    ]);
    }
    
    /* 
    public function actionEtapas(){
          // Mediante DAO
       $dataProvider = new \yii\data\SqlDataProvider([
           'sql' => 'select distinct dorsal from etapa group by dorsal having count(*)>1',
       ]);

       return $this->render("resultado", [
           "resultados" => $dataProvider,
           "campos" => ['dorsal'],
           "titulo" => "Consulta 12 con DAO",
           "enunciado" => "Indícame el dorsal de los ciclistas que hayan ganado más de una etapa",
           "sql" => " select distinct dorsal from etapa group by dorsal having count(*)>1;",
       ]);
        
    }
    */
   public function actionEtapas()
    {
        $sql = 'SELECT e.*, c.nombre AS CiclistaLider
                FROM etapa e
                LEFT JOIN lleva l ON e.numetapa = l.numetapa
                LEFT JOIN ciclista c ON l.dorsal = c.dorsal
                WHERE l.código = :codigo';

        $dataProvider = new SqlDataProvider([
            'sql' => $sql,
            'params' => [':codigo' => 'MGE'],
            'pagination' => [
                'pageSize' => 10, // Ajusta según tus necesidades
            ],
        ]);

        return $this->render('resultado2', [
            'resultados' => $dataProvider,
            'campos' => $dataProvider->getModels() ? array_keys($dataProvider->getModels()[0]) : [],
            'titulo' => 'Consulta de ciclistas',
            'enunciado' => 'Etapas donde el ciclista líder tiene el código MGE',
//            'sql' => $sql,
        ]);
    }
    
   

            public function actionPuertos()
          {
              $dataProvider = new \yii\data\SqlDataProvider([
                  'sql' => 'SELECT nompuerto, altura, pendiente FROM puerto WHERE pendiente > 5.0',
              ]);

              return $this->render('resultado', [
                  'dataProvider' => $dataProvider, // Corregido el nombre de la variable
                  'campos' => ['nompuerto', 'altura', 'pendiente'], // Lista de campos para mostrar en la vista
                  'titulo' => "Consulta de puertos",
                  'enunciado' => "Puertos con pendiente superior al 5%",
              ]);
          }
          
          

            public function actionEquipos()
          {
              $dataProvider = new \yii\data\SqlDataProvider([
                'sql' => 'SELECT COUNT(*) AS total_ciclistas, nomequipo FROM ciclista GROUP BY nomequipo',
            ]);

            return $this->render('resultado', [
                'dataProvider' => $dataProvider,
                'campos' => ['total_ciclistas', 'nomequipo'], // Lista de campos para mostrar en la vista
                'titulo' => "Consulta de Equipos",
                'enunciado' => "Número de Ciclistas por Equipo",
            ]);
          }


        public function actionAlturapuertos()
    {
        $dataProvider = new SqlDataProvider([
            'sql' => 'SELECT nompuerto, altura as altura_puerto FROM puerto GROUP BY nompuerto',
        ]);

        $resultados = $dataProvider->getModels();

        return $this->render('graficopuertos', [
            'dataProvider' => $dataProvider,
            'resultados' => $resultados,
        ]);
    }
    
       public function actionCiclistamge()
    {
        $dataProvider = new SqlDataProvider([
            'sql' => 'select nombre, COUNT(*) AS victorias from lleva inner join ciclista using(dorsal) where código="MGE" group BY dorsal',
        ]);

        $resultados = $dataProvider->getModels();

        return $this->render('graficomge(amarillo)', [
            'dataProvider' => $dataProvider,
            'resultados' => $resultados,
        ]);
    }
    
public function actionMostrarequipo($equipo) {
    
    $director = Equipo::find()->select("director")->distinct()->where(["nomequipo" => $equipo])->scalar();
    
    $ciclistas = Ciclista::find()->select("nombre")->distinct()->where(["nomequipo" => $equipo])->column();
    
    $etapas = Etapa::find()->select("numetapa")->distinct()->orderBy(['numetapa' => SORT_ASC])->column();
    
    $victorias = Etapa::find()->select('etapa.numetapa')->distinct()->innerJoin('ciclista', 'etapa.dorsal = ciclista.dorsal')->where(['ciclista.nomequipo' => $equipo])->column();
    $max_victorias = Etapa::find()->select('MAX(c1.victorias)')->from(['c1' => (new \yii\db\Query())->select('COUNT(*) AS victorias')->from('etapa')->innerJoin('ciclista', 'etapa.dorsal = ciclista.dorsal')->groupBy('ciclista.nomequipo')])->scalar();
    
    $mge = Lleva::find()->select('lleva.numetapa')->distinct()->innerJoin('ciclista', 'lleva.dorsal = ciclista.dorsal')->where(['ciclista.nomequipo' => $equipo, 'lleva.código' => 'mge'])->distinct()->column();
    $mmo = Lleva::find()->select('lleva.numetapa')->distinct()->innerJoin('ciclista', 'lleva.dorsal = ciclista.dorsal')->where(['ciclista.nomequipo' => $equipo, 'lleva.código' => 'mmo'])->distinct()->column();
    $mmv = Lleva::find()->select('lleva.numetapa')->distinct()->innerJoin('ciclista', 'lleva.dorsal = ciclista.dorsal')->where(['ciclista.nomequipo' => $equipo, 'lleva.código' => 'mmv'])->distinct()->column();
    $mre = Lleva::find()->select('lleva.numetapa')->distinct()->innerJoin('ciclista', 'lleva.dorsal = ciclista.dorsal')->where(['ciclista.nomequipo' => $equipo, 'lleva.código' => 'mre'])->distinct()->column();
    $mse = Lleva::find()->select('lleva.numetapa')->distinct()->innerJoin('ciclista', 'lleva.dorsal = ciclista.dorsal')->where(['ciclista.nomequipo' => $equipo, 'lleva.código' => 'mse'])->distinct()->column();
    $mms = Lleva::find()->select('lleva.numetapa')->distinct()->innerJoin('ciclista', 'lleva.dorsal = ciclista.dorsal')->where(['ciclista.nomequipo' => $equipo, 'lleva.código' => 'mms'])->distinct()->column();
    $max_maillots = Lleva::find()->select('MAX(c1.maillots)')->from(['c1' => (new \yii\db\Query())->select('COUNT(*) AS maillots')->from('lleva')->innerJoin('ciclista', 'lleva.dorsal = ciclista.dorsal')->groupBy(['ciclista.nomequipo', 'lleva.código'])])->scalar();
    
    return $this->render('equipo', [
        'equipo' => $equipo,
        'texto' => [

views/layouts/main.php
<?php
/** @var yii\web\View $this */
/** @var string $content */

use app\assets\AppAsset;
use app\widgets\Alert;
use yii\bootstrap4\Breadcrumbs;
use yii\bootstrap4\Html;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" class="h-100">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="author" content="Grupo Alan Turing">
    <meta name="description" content="Aplicación para la gestión de ciclistas.">
    <meta name="keywords" content="HTML, CSS, JavaScript, React">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <?php $this->registerCsrfMetaTags() ?>
    <title>ProBici | Aplicación para la gestión de ciclistas</title>
    <?php $this->head() ?>
    <!-- Favicon -->
    <link rel="shortcut icon" href="favi1.ico" />
    <link rel="icon" type="image/x-icon" href="favicon.ico"/>
</head>
<body class="d-flex flex-column h-100">
<?php $this->beginBody() ?>

<header>
    <?php
    NavBar::begin([
        'brandLabel' => '<div class="d-flex align-items-center">' . 
                        Html::img('@web/images/biciEspa.png', ['alt'=>Yii::$app->name]) .
                        Html::img('@web/images/tit4.png', ['alt'=>'Title Image', 'class'=>'ms-3', 'style'=>'max-height: 100px;']) .
                        '</div>',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar navbar-expand-md navbar-dark bg-dark fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav ml-auto'],
        'items' => [
            ['label' => 'CICLISTAS', 'url' => ['/site/mostrarciclistas']],
            ['label' => 'EQUIPOS', 'url' => ['/site/mostrarequipos']],
            ['label' => 'PUERTOS', 'url' => ['/site/alturapuertos']],
            ['label' => 'VICTORIAS', 'url' => ['/site/ciclistamge']],
            ['label' => 'MAILLOTS', 'url' => ['/site/mostrarmaillots']],
           /* ['label' => 'About', 'url' => ['/site/about']],
            ['label' => 'Contact', 'url' => ['/site/contact']],
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post', ['class' => 'form-inline'])
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            ) */
        ],
    ]);
    NavBar::end();
    ?>
</header>

<main role="main" class="flex-shrink-0">
    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</main>

<footer class="footer mt-auto py-3 text-muted">
    <div class="container">
        <p class="float-left">&copy; Alan Turing <?= date('Y') ?></p>
        <p class="float-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>