controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\data\ActiveDataProvider;
use app\models\Ciclista;
use app\models\Equipo;
use app\models\Puerto;
use app\models\Lleva;
use app\models\Etapa;
use yii\data\SqlDataProvider;
use yii\db\Query;


class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
    
    
    
    /*Este método se usa para mostrar el ListView*/
    public function actionMostrarciclistas(){
        $dataProvider = new ActiveDataProvider ([
            'query' => Ciclista::find(),
        ]);
        return $this->render("ciclistas",[
            "dataProvider"=>$dataProvider,
        ]);
    }
     
    
    public function actionMostrarequipos(){
        $dataProvider = new ActiveDataProvider([
        'query' => Equipo::find(),
        'pagination' => [
            'pageSize' => 12, // Ajusta según sea necesario
        ],
    ]);

    return $this->render('equiposs', [
        'dataProvider' => $dataProvider,
    ]);
    }
    
    /* 
    public function actionEtapas(){
          // Mediante DAO
       $dataProvider = new \yii\data\SqlDataProvider([
           'sql' => 'select distinct dorsal from etapa group by dorsal having count(*)>1',
       ]);

       return $this->render("resultado", [
           "resultados" => $dataProvider,
           "campos" => ['dorsal'],
           "titulo" => "Consulta 12 con DAO",
           "enunciado" => "Indícame el dorsal de los ciclistas que hayan ganado más de una etapa",
           "sql" => " select distinct dorsal from etapa group by dorsal having count(*)>1;",
       ]);
        
    }
    */
   public function actionEtapas()
    {
        $sql = 'SELECT e.*, c.nombre AS CiclistaLider
                FROM etapa e
                LEFT JOIN lleva l ON e.numetapa = l.numetapa
                LEFT JOIN ciclista c ON l.dorsal = c.dorsal
                WHERE l.código = :codigo';

        $dataProvider = new SqlDataProvider([
            'sql' => $sql,
            'params' => [':codigo' => 'MGE'],
            'pagination' => [
                'pageSize' => 10, // Ajusta según tus necesidades
            ],
        ]);

        return $this->render('resultado2', [
            'resultados' => $dataProvider,
            'campos' => $dataProvider->getModels() ? array_keys($dataProvider->getModels()[0]) : [],
            'titulo' => 'Consulta de ciclistas',
            'enunciado' => 'Etapas donde el ciclista líder tiene el código MGE',
//            'sql' => $sql,
        ]);
    }
    
   

            public function actionPuertos()
          {
              $dataProvider = new \yii\data\SqlDataProvider([
                  'sql' => 'SELECT nompuerto, altura, pendiente FROM puerto WHERE pendiente > 5.0',
              ]);

              return $this->render('resultado', [
                  'dataProvider' => $dataProvider, // Corregido el nombre de la variable
                  'campos' => ['nompuerto', 'altura', 'pendiente'], // Lista de campos para mostrar en la vista
                  'titulo' => "Consulta de puertos",
                  'enunciado' => "Puertos con pendiente superior al 5%",
              ]);
          }
          
          

            public function actionEquipos()
          {
              $dataProvider = new \yii\data\SqlDataProvider([
                'sql' => 'SELECT COUNT(*) AS total_ciclistas, nomequipo FROM ciclista GROUP BY nomequipo',
            ]);

            return $this->render('resultado', [
                'dataProvider' => $dataProvider,
                'campos' => ['total_ciclistas', 'nomequipo'], // Lista de campos para mostrar en la vista
                'titulo' => "Consulta de Equipos",
                'enunciado' => "Número de Ciclistas por Equipo",
            ]);
          }


        public function actionAlturapuertos()
    {
        $dataProvider = new SqlDataProvider([
            'sql' => 'SELECT nompuerto, altura as altura_puerto FROM puerto GROUP BY nompuerto',
        ]);

        $resultados = $dataProvider->getModels();

        return $this->render('graficopuertos', [
            'dataProvider' => $dataProvider,
            'resultados' => $resultados,
        ]);
    }
    
       public function actionCiclistamge()
    {
        $dataProvider = new SqlDataProvider([
            'sql' => 'select nombre, COUNT(*) AS victorias from lleva inner join ciclista using(dorsal) where código="MGE" group BY dorsal',
        ]);

        $resultados = $dataProvider->getModels();

        return $this->render('graficomge(amarillo)', [
            'dataProvider' => $dataProvider,
            'resultados' => $resultados,
        ]);
    }
    
public function actionMostrarequipo($equipo) {
    
    $director = Equipo::find()->select("director")->distinct()->where(["nomequipo" => $equipo])->scalar();
    
    $ciclistas = Ciclista::find()->select("nombre")->distinct()->where(["nomequipo" => $equipo])->column();
    
    $etapas = Etapa::find()->select("numetapa")->distinct()->orderBy(['numetapa' => SORT_ASC])->column();
    
    $victorias = Etapa::find()->select('etapa.numetapa')->distinct()->innerJoin('ciclista', 'etapa.dorsal = ciclista.dorsal')->where(['ciclista.nomequipo' => $equipo])->column();
    $max_victorias = Etapa::find()->select('MAX(c1.victorias)')->from(['c1' => (new \yii\db\Query())->select('COUNT(*) AS victorias')->from('etapa')->innerJoin('ciclista', 'etapa.dorsal = ciclista.dorsal')->groupBy('ciclista.nomequipo')])->scalar();
    
    $mge = Lleva::find()->select('lleva.numetapa')->distinct()->innerJoin('ciclista', 'lleva.dorsal = ciclista.dorsal')->where(['ciclista.nomequipo' => $equipo, 'lleva.código' => 'mge'])->distinct()->column();
    $mmo = Lleva::find()->select('lleva.numetapa')->distinct()->innerJoin('ciclista', 'lleva.dorsal = ciclista.dorsal')->where(['ciclista.nomequipo' => $equipo, 'lleva.código' => 'mmo'])->distinct()->column();
    $mmv = Lleva::find()->select('lleva.numetapa')->distinct()->innerJoin('ciclista', 'lleva.dorsal = ciclista.dorsal')->where(['ciclista.nomequipo' => $equipo, 'lleva.código' => 'mmv'])->distinct()->column();
    $mre = Lleva::find()->select('lleva.numetapa')->distinct()->innerJoin('ciclista', 'lleva.dorsal = ciclista.dorsal')->where(['ciclista.nomequipo' => $equipo, 'lleva.código' => 'mre'])->distinct()->column();
    $mse = Lleva::find()->select('lleva.numetapa')->distinct()->innerJoin('ciclista', 'lleva.dorsal = ciclista.dorsal')->where(['ciclista.nomequipo' => $equipo, 'lleva.código' => 'mse'])->distinct()->column();
    $mms = Lleva::find()->select('lleva.numetapa')->distinct()->innerJoin('ciclista', 'lleva.dorsal = ciclista.dorsal')->where(['ciclista.nomequipo' => $equipo, 'lleva.código' => 'mms'])->distinct()->column();
    $max_maillots = Lleva::find()->select('MAX(c1.maillots)')->from(['c1' => (new \yii\db\Query())->select('COUNT(*) AS maillots')->from('lleva')->innerJoin('ciclista', 'lleva.dorsal = ciclista.dorsal')->groupBy(['ciclista.nomequipo', 'lleva.código'])])->scalar();
    
    return $this->render('equipo', [
        'equipo' => $equipo,
        'texto' => [

views/site/_ciclistas.php
<?php
use yii\helpers\Html;
use yii\widgets\DetailView;

// $model representa un modelo de ciclista que será proporcionado por el ListView
?>


<!--Este es el código que determina cómo se muestran los datos y qué maquetación tienen en el ListView-->
<div class="media">
    <div class="media-body">
        <h4 class="media-heading"><?= Html::encode($model->nombre) ?></h4>
        <p><?= 'Edad: ' . Html::encode($model->edad) ?></p>
        <p><?= 'Dorsal: ' . Html::encode($model->dorsal) ?></p>
        <p><?= 'Equipo: ' . Html::encode($model->nomequipo) ?></p>
    </div>
</div>

views/site/_equipos.php
<?php
    use yii\helpers\Html;
?>

<div class="body-content">
    <div class="row">
        <div class="col-sm-8 col-md-10 mb-4">
             <div>
                 <div class="tarjeta-equipo">
                        <?= Html::img('@web/images/' . $model->nomequipo . '.png') ?>
                        <?= Html::a($model->nomequipo, ['site/mostrarequipo', 'equipo' => strtolower($model->nomequipo)], ['class'=>'btn btn-outline-primary']) ?>
                 </div>
             </div>
         </div>
    </div>
</div>

views/site/ciclistas.php
<?php

use yii\helpers\Html;
use yii\widgets\ListView;
use yii\bootstrap\BootstrapAsset;
use yii\widgets\LinkPager;

// Definición del título
$this->title = 'Los ciclistas';

?>


<div class="body-content mt-5">
    <style>
            .body-content {
          margin-left: 80px;
      }

      /* Ajuste para evitar que el margen afecte al header y al footer */
      header, footer {
          margin-left: 0px;
          width: calc(100% + 80px);
      }
    </style>
    <div class="row">
    <?= ListView::widget([
        'dataProvider' => $dataProvider,
        'itemView' => '_ciclistas',
        'layout' => "{items}",
        'options' => ['class' => 'row'], // Clase de Bootstrap
        'itemOptions' => ['class' => 'col-sm-4 mb-3'], // Clase de Bootstrap para cada elemento
    ]); ?>
    </div>
</div>
<div class="row">
        <div class="col-sm-12 text-center"> <!-- Centra la paginación -->
            <?= LinkPager::widget([
                'pagination' => $dataProvider->pagination,
            ]); ?>
        </div>
    </div>

views/site/contact.php
<?php

/** @var yii\web\View $this */
/** @var yii\bootstrap4\ActiveForm $form */
/** @var app\models\ContactForm $model */

use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/equipo.php
<?php

    use yii\helpers\Html;
    use dosamigos\highcharts\HighCharts;

    $this->title = $equipo;
    
    
    $data_victorias = [];
    $total_victorias = 0;
    
    foreach ($etapas as $etapa) {
        if (in_array($etapa, $victorias)) {
            $total_victorias++;
        }
        $data_victorias[] = [
            'name' => 'Etapa ' . $etapa,
            'y' => $total_victorias,
        ];
    }

    $etapas_names = array_map(function($etapa) {
        return 'Etapa ' . $etapa;
    }, $etapas);

    $chart_victorias = [
        'chart' => ['type' => 'line'],
        'title' => ['text' => 'Victorias del equipo'],
        'xAxis' => ['categories' => array_slice($etapas_names, 0),],
        'yAxis' => [
            'title' => ['text' => 'Número de victorias'],
            'min' => 0,
            'max' => $max_victorias,
        ],
        'series' => [['name' => 'Victorias', 'data' => $data_victorias]],
    ];
    
    $data_mge = [];
    $total_mge = 0;
    
    foreach ($etapas as $etapa) {
        if (in_array($etapa, $mge)) {
            $total_mge++;
        }
        $data_mge[] = [
            'name' => 'Etapa ' . $etapa,
            'y' => $total_mge,
        ];
    }
    
    $data_mmo = [];
    $total_mmo = 0;
    
    foreach ($etapas as $etapa) {
        if (in_array($etapa, $mmo)) {
            $total_mmo++;
        }
        $data_mmo[] = [
            'name' => 'Etapa ' . $etapa,
            'y' => $total_mmo,
        ];
    }
    
    $data_mmv = [];
    $total_mmv = 0;
    
    foreach ($etapas as $etapa) {
        if (in_array($etapa, $mmv)) {
            $total_mmv++;
        }
        $data_mmv[] = [
            'name' => 'Etapa ' . $etapa,
            'y' => $total_mmv,
        ];
    }
    
    $data_mre = [];
    $total_mre = 0;
    
    foreach ($etapas as $etapa) {
        if (in_array($etapa, $mre)) {
            $total_mre++;
        }
        $data_mre[] = [
            'name' => 'Etapa ' . $etapa,
            'y' => $total_mre,
        ];
    }
    
    $data_mse = [];
    $total_mse = 0;
    
    foreach ($etapas as $etapa) {
        if (in_array($etapa, $mse)) {
            $total_mse++;
        }
        $data_mse[] = [
            'name' => 'Etapa ' . $etapa,
            'y' => $total_mse,
        ];
    }
    
    $data_mms = [];
    $total_mms = 0;
    
    foreach ($etapas as $etapa) {
        if (in_array($etapa, $mms)) {
            $total_mms++;
        }
        $data_mms[] = [
            'name' => 'Etapa ' . $etapa,
            'y' => $total_mms,
        ];
    }
    
    $chart_maillots = [
        'chart' => ['type' => 'line'],
        'title' => ['text' => 'Maillots obtenidos'],
        'xAxis' => ['categories' => array_slice($etapas_names, 0),],
        'yAxis' => [
            'title' => ['text' => 'Número de maillots'],
            'min' => 0,
            'max' => $max_maillots,
        ],
        'colors' => ['#FFFF00', '#ff9E81', '#800080', '#FF0000', '#008000', '#FFC0C0'],
        'series' => [['name' => 'MGE', 'data' => $data_mge], ['name' => 'MMO', 'data' => $data_mmo], ['name' => 'MMV', 'data' => $data_mmv], ['name' => 'MRE', 'data' => $data_mre], ['name' => 'MSE', 'data' => $data_mse], ['name' => 'MMS', 'data' => $data_mms]]
    ];
    
?>


<div class="site-index">
    
    <div class="jumbotron text-center" style="background-image: url('https://images.pexels.com/photos/2876511/pexels-photo-2876511.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'); background-size: cover; background-position: center; color: #FFBD59;">
        <h1 class="display-4"><?= strtoupper($equipo) ?></h1>
    </div>

    <div class="container" style="margin-top: -64px !important;">
        
        <div class="row justify-content-center">
            <div class="col-md-7">
                <p class="text-justify"><?= $texto[$equipo] ?></p>
            </div>
            <div class="col-md-3">
                <?= Html::img('@web/images/banner_' . $equipo . '.jpg', ['alt' => 'Banner ' . ucwords($equipo), 'class' => 'img-fluid']) ?>
            </div>
        </div>
        
        <hr class="my-4">
        
        <div class="row justify-content-center">
            <div class="col-md-3">
                <h4 class="text-center">COMPONENTES DEL EQUIPO</h4>
                <p style="font-weight: bold"><?= ucwords($director) ?> (D)</p>
                <?php foreach ($ciclistas as $ciclista): ?>
                    <p style="font-weight: bold"><?= ucwords($ciclista) ?></p>
                <?php endforeach; ?>
            </div>
            <div class="col-md-7">
                <?= HighCharts::widget(['clientOptions' => $chart_victorias]); ?>
            </div>
        </div>
        
        <hr class="my-4">
        
        <div class="row justify-content-center">
            <div class="col-md-10">
                <?= HighCharts::widget(['clientOptions' => $chart_maillots]); ?>
            </div>
        </div>
        
    </div>

</div>

views/site/equiposs.php
<?php

use yii\helpers\Html;
use yii\widgets\ListView;
use yii\bootstrap\BootstrapAsset;
use yii\widgets\LinkPager;

// Definición del título
$this->title = 'Los equipos';

?>


<div class="body-content mt-5">
       <style>
            .body-content {
          margin-left: 15px;
      }

      /* Ajuste para evitar que el margen afecte al header y al footer */
      header, footer {
          margin-left: 0px;
          width: calc(100% + 80px);
      }
    </style>
    <div class="row">
        <?= ListView::widget([
            'dataProvider' => $dataProvider,
            'itemView' => '_equipos', // Vista parcial para cada tarjeta
            'layout' => "{items}",
            'options' => ['class' => 'row'], // Agregado para envolver las tarjetas en una fila
            'itemOptions' => ['class' => 'col-sm-4 col-md-3 mb-3'], // Ajustado para ocupar 4 unidades en pantallas pequeñas
        ]); ?>
    </div>
</div>

<div class="row">
        <div class="col-sm-12 text-center"> <!-- Centra la paginación -->
            <?= LinkPager::widget([
                'pagination' => $dataProvider->pagination,
            ]); ?>
        </div>
    </div>

views/site/error.php
<?php

/** @var yii\web\View $this */
/** @var string $name */
/** @var string $message */
/** @var Exception$exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/graficomge(amarillo).php
<?php

use yii\helpers\Html;
use yii\helpers\Json;
use dosamigos\highcharts\HighCharts;

$data = [];
foreach ($resultados as $resultado) {
    $data[] = [
        'name' => $resultado['nombre'],
        'y' => (float) $resultado['victorias'], // Cambiado a float para aceptar valores decimales
    ];
}

$chartConfig = [
    'chart' => ['type' => 'pie'],
    'title' => ['text' => 'Cantidad de maillots amarilos ganados por estos cilistas'],
    'xAxis' => ['categories' => array_column($resultados, 'nombre')],
    'yAxis' => ['title' => ['text' => 'Victorias del ciclista']],
    'series' => [['name' => 'Victorias del ciclista', 'data' => $data]],
];

echo HighCharts::widget(['clientOptions' => $chartConfig]);

echo Html::tag('div', '', ['id' => 'grafico-puerto']);

//Texto e imagenes después del gráfico
echo '<div>';
echo '<div class="d-flex align-items-center">';
echo '<div style="margin-left: 200px;">'; // Margen a la izquierda de la imagen
echo Html::img('@web/images/indurain2.jpg', ['alt' => Yii::$app->name, 'style' => 'padding-top: 20px;']); // Añadir padding-top a la imagen
echo '</div>';
echo '<div style="margin-top: 50px;">'; // Margen superior del texto
echo '<h2 style="padding-right: 25%; padding-left: 10%;">Miguel Induráin
</h2>';
echo '<h3 style="padding-right: 25%; padding-left: 10%;">Dorsal: 1  Edad: 32  Equipo: Banesto
</h3>';
echo '<p style="padding-right: 25%; padding-left: 10%;">Indurain alcanzó la fama internacional en la década de 1990, cuando dominó el Tour de Francia de una manera que pocos ciclistas habían hecho antes. Su época dorada comenzó en 1991, cuando ganó su primer Tour de Francia, convirtiéndose en el primer ciclista español en lograrlo. Lo que siguió fue una racha increíble de cinco victorias consecutivas en el Tour, de 1991 a 1995, un récord que aún no ha sido superado.</p>';
echo '</div>';
echo '</div>';
echo '</div>';


echo '<div>';
echo '<div class="d-flex align-items-center">';
echo '<div style="margin-left: 200px;">'; // Margen a la izquierda de la imagen
echo Html::img('@web/images/tomy2.jpg', ['alt' => Yii::$app->name, 'style' => 'padding-top: 20px;']); // Añadir padding-top a la imagen
echo '</div>';
echo '<div style="margin-top: 50px;">'; // Margen superior del texto
echo '<h2 style="padding-right: 25%; padding-left: 10%;">Tony Rominger
</h2>';
echo '<h3 style="padding-right: 25%; padding-left: 10%;">Edad: 30  Dorsal: 4  Equipo: Mapei-Clas
</h3>';
echo '<p style="padding-right: 25%; padding-left: 10%;">Su carrera profesional en el ciclismo comenzó en la década de 1980, y rápidamente se destacó como un escalador formidable y un contrarrelojista excepcional. Sin embargo, fue en la década de 1990 cuando Rominger alcanzó la cima de su carrera, logrando una serie de victorias impresionantes que lo catapultaron a la fama mundial.</p>';
echo '</div>';
echo '</div>';
echo '</div>';


// Renderizamos el gráfico HighCharts
$this->registerJsFile('@web/js/highcharts.js', ['depends' => [\yii\web\JqueryAsset::class]]);
$this->registerJsFile('@web/js/exporting.js', ['depends' => [\yii\web\JqueryAsset::class]]);
$this->registerJsFile('@web/js/export-data.js', ['depends' => [\yii\web\JqueryAsset::class]]);
$this->registerCssFile('@web/css/highcharts.css');

views/site/index.php
<?php
/*  */
/** @var yii\web\View $this */
use yii\helpers\Url;

$this->title = 'My Yii Application';
?>

<?php 
// Registra el archivo JavaScript
$this->registerJsFile('@web/js/prueba.js', ['depends' => [\yii\web\JqueryAsset::class]]);
?>


<div class="site-index">

    
    <div class="jumbotron text-color text-center" style="background-image: url('https://images.pexels.com/photos/2876511/pexels-photo-2876511.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'); background-size: cover; background-position: center;">
       
    </div>

        <!-- Introducción breve -->
    <div class="intro-section text-center">
        <h2>Revive <span id="dynamic-word"></span></h2>
        <p>Sumérgete en la emocionante historia de la Vuelta Ciclista a España a través de nuestra aplicación. Revive momentos legendarios, descubre datos históricos y explora la pasión por el ciclismo en cada edición. La Retrovuelta te invita a explorar el pasado de esta icónica carrera y a compartir la emoción por el ciclismo. ¡Únete a nosotros en este viaje por la historia de la Vuelta!</p>
    </div>
        
        
        

    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="./images/image2.jpg" alt="Image 1">
            </div>  
            <div class="carousel-item">
                <img src="./images/85E_2866.jpg" alt="Image 2">
            </div>
            <div class="carousel-item">
                <img src="./images/image3.jpg" alt="Image 3">
            </div>
        </div>
    </div>  

   
    
<div class="card-deck text-center mt-2">
    <style>
        .card-body:hover {
    background-color: #AD3333 !important;
}
    </style>
    <div class="card mx-2">
        <a href="<?= Url::to('site/puertos') ?>" class="card-body btn btn" data-title="Puertos">
            <img src="<?= Yii::getAlias('@web') ?>/images/Montaña.png" alt="Etapas">
        </a>
    </div>
    <div class="card mx-2">
        <a href="<?= Url::to(['site/etapas']) ?>" class="card-body btn btn-sm" data-title="Maillot Amarillo">
            <img src="<?= Yii::getAlias('@web') ?>/images/Maillot.png" alt="Puertos">
        </a>
    </div>
    <div class="card mx-2">
        <a href="<?= Url::to(['site/equipos']) ?>" class="card-body btn btn-sm" data-title="Equipos">
            <img src="<?= Yii::getAlias('@web') ?>/images/ciclista.png" alt="Equipos">
        </a>
    </div>
</div>
    
        
 


    
</div>